### ISSUE TITLE
Open Safely

### ISSUE THREAD

**Issue by polc1410** [StatsGary/NHSDataDictionaRy#4]
I've added a pull request to pull a function to download code lists from  @OpenSafely.

While the OpenSafely lists are good if you want to reproduce data, I can see some real use for other projects across the NHS if you wanted to build a list of diagnosis and search for it etc.  OpenSafely makes building the list easy, and storing and version controlling it.

**Comment by StatsGary** [comment]
@all-contributors please add @polc1410  for design
